version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"  # Map MySQL container port 3306 to host port 3307
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"  # Map server container port 8080 to host port 8080
    depends_on:
      - mysql
    restart: always

volumes:
  mysql-data:
    driver: local
