version: '3.8'

services:
  mysql:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bike-lending-network
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - bike-lending-network
    restart: always

volumes:
  mysql-data:
    driver: local

networks:
  bike-lending-network:
    driver: bridge
