name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Clean and compile the project
        run: |
          cd bike-lending-app
          mvn --batch-mode clean compile
          
      - name: Prepare database for testing
        run: | 
          sudo /etc/init.d/mysql start
          cd bike-lending-app
          mysql -uroot -proot < sql/create-bikes.sql
          mvn --batch-mode --update-snapshots datanucleus:enhance datanucleus:schema-create
          
      - name: Start the server in the background
        run: |
          cd bike-lending-app
          mvn --batch-mode jetty:run &
          sleep 10

      - name: Run the unit tests
        run: |
          cd bike-lending-app
          mvn test

      - name: Generate JaCoCo report
        run: |
          cd bike-lending-app
          mvn jacoco:report

      - name: Execute integration tests
        run: |
          cd bike-lending-app
          mvn --batch-mode --update-snapshots verify -Pintegration-tests

      - name: Execute performance tests
        run: |
          cd bike-lending-app
          mvn --batch-mode --update-snapshots verify -Pperformance-tests

  document:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this line is correctly added
      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Generate documentation
        run: |
          cd bike-lending-app
          mvn doxygen:report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: bike-lending-app/target/doxygen/html
          publish_branch: gh-pages
          keep_files: true
          destination_dir: doxygen

      - name: Deploy JaCoCo report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: bike-lending-app/target/site/jacoco
          publish_branch: gh-pages
          keep_files: true
          destination_dir: jacoco

      

  package:
    needs: document
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Package the application
        run: |
          cd bike-lending-app
          mvn package -DskipTests -DskipITs

  